In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
from utils import (
    select_users_by_period,
    create_hourly_user_dataset,
    compute_position_metrics,
)
from visualization_utils import (
    plot_market_features,
    plot_user_metrics,
)
# from visualization_utils import plot_user_metrics

In [3]:
import os
import pandas as pd
from tqdm.auto import tqdm
import re
from datetime import datetime


def add_yield_to_actions(actions_df, yield_df):
    df = actions_df.copy()
    yield_df = yield_df.copy()
    yield_df['timestamp'] = pd.to_datetime(yield_df['timestamp']).astype('int64') // 10**9
    
    # Get min and max timestamps from yield data
    yield_min = yield_df['timestamp'].min()
    yield_max = yield_df['timestamp'].max()
    
    # Filter actions
    df = df[(df['timestamp'] >= yield_min) & (df['timestamp'] <= yield_max + 30 * 24 * 60 * 60)]
    df = df.sort_values('timestamp')
    yield_df = yield_df.sort_values('timestamp')
    df = pd.merge_asof(
        df,
        yield_df[['timestamp', 'base_apy', 'implied_apy', 'underlying_apy']],
        on='timestamp',
        direction='nearest'
    )
    
    return df


from datetime import datetime

def parse_expiry_from_token(token_name):
    parts = token_name.split('-')
    for part in parts:
        if len(part) == 9 and part[:2].isdigit() and part[2:5].isalpha() and part[5:].isdigit():
            # format DDMMMYYYY e.g., 25SEP2025
            return datetime.strptime(part, '%d%b%Y')
    return None
def build_position_statistics(df_actions, token_name):
    expiry = parse_expiry_from_token(token_name)
    if expiry is None:
        raise ValueError(f"Cannot parse expiry from token name: {token_name}")
    expiry_ts = expiry.timestamp()
    
    # Get users with at least one position_open
    open_users = df_actions[df_actions['action'] == 'position_open']['user_address'].unique()
    
    results = []
    for user in open_users:
        user_df = df_actions[df_actions['user_address'] == user].sort_values('timestamp')
        
        # Find first open and first close after that
        open_rows = user_df[user_df['action'] == 'position_open']
        if open_rows.empty:
            continue
        open_time = open_rows.iloc[0]['timestamp']
        open_dt = open_rows.iloc[0]['datetime']
        open_ltv = open_rows.iloc[0]['ltv']
        open_debt = open_rows.iloc[0]['debt']
        
        close_rows = user_df[(user_df['action'] == 'position_close') & (user_df['timestamp'] > open_time)]
        if close_rows.empty:
            continue
        close_time = close_rows.iloc[0]['timestamp']
        close_dt = close_rows.iloc[0]['datetime']
        
        # Subset rows between open and close (inclusive)
        position_df = user_df[(user_df['timestamp'] >= open_time) & (user_df['timestamp'] <= close_time)]
        
        max_debt = position_df['debt'].max()
        max_ltv = position_df['ltv'].max()
        min_ltv = position_df[position_df["ltv"] > 0.1]['ltv'].min()
        
        pos_days = (close_time - open_time) / (24 * 3600)
        days_to_expiry = (expiry_ts - close_time) / (24 * 3600)
        
        results.append({
            'user_address': user,
            'opening_date': open_dt,
            'closing_date': close_dt,
            'position_length_days': pos_days,
            'max_debt': max_debt,
            'max_ltv': max_ltv,
            'min_ltv': min_ltv,
            'initial_ltv': open_ltv,
            'initial_debt': open_debt,
            'days_to_expiry_after_close': days_to_expiry
        })
    
    return pd.DataFrame(results)


def parse_expiry_from_token(token_name):
    # Look for pattern: DDMMMYYYY or DMMMYYYY (where D is digit, MMM is month, YYYY is year)
    match = re.search(r'(\d{1,2}[A-Za-z]{3}\d{4})', token_name)
    if match:
        date_str = match.group(1)
        # Pad day to 2 digits if needed
        if len(date_str) == 8:  # DMMMYYYY format
            date_str = '0' + date_str
        return datetime.strptime(date_str, '%d%b%Y')
    raise ValueError(f"Cannot parse expiry from {token_name}")

def collect_position_metrics_for_all_pt_markets(
    events_dir="/Users/yegortrussov/Documents/ml/lending_protocols/dataset_collection/data/markets_enriched",
    hourly_dir="/Users/yegortrussov/Documents/ml/lending_protocols/dataset_collection/data/markets_hourly_data",
    yields_dir="/Users/yegortrussov/Documents/ml/lending_protocols/dataset_collection/data/pt_yields",
):
    """
    Iterate over all PT-* markets in events_dir, compute position statistics,
    and return a list of dicts with keys: token, market_name, positions_df.
    """
    results = []
    # List all CSV files in events_dir
    for fname in os.listdir(events_dir):
        if not fname.endswith('.csv'):
            continue
        market_name = fname[:-4]  # remove .csv
        # Check if market name starts with "PT-"
        if not market_name.startswith("eth_PT-"):
            continue
        # Extract token name (e.g., PT-USDe-25SEP2025)
        token_name = market_name.split('_')[1]  # assuming format PT-..._usdc
        try:
            expiry = parse_expiry_from_token(token_name)
        except Exception as e:
            continue
        threshold_date = (expiry + pd.Timedelta(days=10)).strftime('%Y-%m-%d')
        # Paths
        events_path = os.path.join(events_dir, fname)
        hourly_path = os.path.join(hourly_dir, f"{market_name}.csv")
        yields_path = os.path.join(yields_dir, f"{token_name}.csv")
        
        # Check if required files exist
        if not os.path.exists(hourly_path):
            print(f"Missing hourly data for {market_name}, skipping")
            continue
        if not os.path.exists(yields_path):
            print(f"Missing yield data for {token_name}, skipping")
            continue
        
        try:
            # Load data
            print(f"Processing market {market_name} (expirity {expiry})... ")
            df = pd.read_csv(events_path)
            market_df = pd.read_csv(hourly_path)
            yield_df = pd.read_csv(yields_path).sort_values("timestamp")
            
            # Add yields to actions
            df = add_yield_to_actions(df, yield_df)
            market_df = add_yield_to_actions(market_df, yield_df)
            
            # Create hourly user dataset
            hourly = create_hourly_user_dataset(
                df,
                market_df,
                n_hours=1,
                threshold_date=threshold_date,
                additional_action_features=["implied_apy"]
            )
            
            # Build position statistics
            pos_stats = build_position_statistics(hourly, token_name)
            
            results.append({
                'token': token_name,
                'market_name': market_name,
                'positions_df': pos_stats,
                'market_df': market_df,
                'raw_df': df,
                'hourly_df': hourly,
            })
            print(f"Processed {market_name}: {len(pos_stats)} positions")
        except Exception as e:
            print(f"Error processing {market_name}: {e}")
            continue
    
    return results

all_markets_position = collect_position_metrics_for_all_pt_markets()

Processing market eth_PT-syrupUSDC-28AUG2025_usdc (expirity 2025-08-28 00:00:00)...
Processed eth_PT-syrupUSDC-28AUG2025_usdc: 15 positions
Processing market eth_PT-slvlUSD-25SEP2025_usdc (expirity 2025-09-25 00:00:00)...
Processed eth_PT-slvlUSD-25SEP2025_usdc: 76 positions
Processing market eth_PT-USDe-27NOV2025_usds (expirity 2025-11-27 00:00:00)...
Processed eth_PT-USDe-27NOV2025_usds: 35 positions
Processing market eth_PT-USDe-25SEP2025_dai (expirity 2025-09-25 00:00:00)...
Processed eth_PT-USDe-25SEP2025_dai: 128 positions
Processing market eth_PT-syrupUSDC-30OCT2025_usdc (expirity 2025-10-30 00:00:00)...
Processed eth_PT-syrupUSDC-30OCT2025_usdc: 10 positions
Missing yield data for PT-USDe-26DEC2024, skipping
Processing market eth_PT-stcUSD-23JUL2026_usdc (expirity 2026-07-23 00:00:00)...
Processed eth_PT-stcUSD-23JUL2026_usdc: 3 positions
Processing market eth_PT-USDe-27NOV2025_usdc (expirity 2025-11-27 00:00:00)...
Processed eth_PT-USDe-27NOV2025_usdc: 2 positions
Missing yield data for PT-sNUSD-4JUN2026, skipping
Processing market eth_PT-wstUSR-27MAR2025_usr (expirity 2025-03-27 00:00:00)...
Processed eth_PT-wstUSR-27MAR2025_usr: 51 positions
Missing yield data for PT-mHYPER-29JAN2026, skipping
Processing market eth_PT-sNUSD-5MAR2026_usdc (expirity 2026-03-05 00:00:00)...
Processed eth_PT-sNUSD-5MAR2026_usdc: 6 positions
Missing yield data for PT-lvlUSD-25SEP2025, skipping
Processing market eth_PT-USD0++-31OCT2024_usdc (expirity 2024-10-31 00:00:00)...
Processed eth_PT-USD0++-31OCT2024_usdc: 23 positions
Processing market eth_PT-USDe-31JUL2025_dai (expirity 2025-07-31 00:00:00)...
Processed eth_PT-USDe-31JUL2025_dai: 95 positions
Processing market eth_PT-USDe-25SEP2025_usdt (expirity 2025-09-25 00:00:00)...
Processed eth_PT-USDe-25SEP2025_usdt: 116 positions
Processing market eth_PT-USDe-25SEP2025_usdc (expirity 2025-09-25 00:00:00)...
Processed eth_PT-USDe-25SEP2025_usdc: 216 positions
Missing yield data for PT-USR-4DEC2025, skipping
Processing market eth_PT-wstUSR-27MAR2025_usdc (expirity 2025-03-27 00:00:00)...
Processed eth_PT-wstUSR-27MAR2025_usdc: 10 positions
Missing yield data for PT-USR-4SEP2025, skipping
Processing market eth_PT-slvlUSD-29MAY2025_usdc (expirity 2025-05-29 00:00:00)...
Processed eth_PT-slvlUSD-29MAY2025_usdc: 35 positions
Processing market eth_PT-mHYPER-20NOV2025_usdc (expirity 2025-11-20 00:00:00)...
Processed eth_PT-mHYPER-20NOV2025_usdc: 77 positions
Missing yield data for PT-syrupUSDC-18DEC2025, skipping
Processing market eth_PT-reUSD-25JUN2026_usdc (expirity 2026-06-25 00:00:00)...
Processed eth_PT-reUSD-25JUN2026_usdc: 223 positions
Missing yield data for PT-USD0++-26JUN2025, skipping
Processing market eth_PT-reUSD-18DEC2025_usdc (expirity 2025-12-18 00:00:00)...
Processed eth_PT-reUSD-18DEC2025_usdc: 21 positions
Processing market eth_PT-RLP-4SEP2025_usdc (expirity 2025-09-04 00:00:00)...
Processed eth_PT-RLP-4SEP2025_usdc: 63 positions
Processing market eth_PT-csUSDL-31JUL2025_usdc (expirity 2025-07-31 00:00:00)...
Processed eth_PT-csUSDL-31JUL2025_usdc: 107 positions
Missing yield data for PT-mHYPER-30APR2026, skipping
Processing market eth_PT-wstUSR-25SEP2025_usdc (expirity 2025-09-25 00:00:00)...
Processed eth_PT-wstUSR-25SEP2025_usdc: 60 positions
Processing market eth_PT-stcUSD-29JAN2026_usdc (expirity 2026-01-29 00:00:00)...
Processed eth_PT-stcUSD-29JAN2026_usdc: 129 positions
Processing market eth_PT-lvlUSD-29MAY2025_usdc (expirity 2025-05-29 00:00:00)...
Processed eth_PT-lvlUSD-29MAY2025_usdc: 85 positions
Processing market eth_PT-USR-29MAY2025_usdc (expirity 2025-05-29 00:00:00)...
Processed eth_PT-USR-29MAY2025_usdc: 18 positions
Processing market eth_PT-USDe-27MAR2025_dai (expirity 2025-03-27 00:00:00)...
Processed eth_PT-USDe-27MAR2025_dai: 122 positions
Missing yield data for PT-csUSDL-30OCT2025, skipping
Missing yield data for PT-RLP-9APR2026, skipping
Processing market eth_PT-USD0++-27MAR2025_usdc (expirity 2025-03-27 00:00:00)...
Processed eth_PT-USD0++-27MAR2025_usdc: 42 positions

In [6]:
# all_markets_position[0]['positions_df']['closing_date']
# rw = all_markets_position[0]['raw_df']
# openers = []
# suppliers_shares = 
# addrs = all_markets_position[0]['raw_df']['user_address']


import pandas as pd
from datetime import datetime
import re

def parse_expiry_from_token(token_name):
    """Extract expiry date from token name like 'PT-syrupUSDC-28AUG2025'."""
    match = re.search(r'(\d{1,2}[A-Za-z]{3}\d{4})', token_name)
    if match:
        date_str = match.group(1)
        if len(date_str) == 8:
            date_str = '0' + date_str
        return datetime.strptime(date_str, '%d%b%Y')
    return None

def get_base_token(token_name):
    """Extract base token without expiry, e.g., 'PT-syrupUSDC-28AUG2025' -> 'PT-syrupUSDC'."""
    # Remove the last part after last '-' (the expiry date)
    parts = token_name.split('-')
    # Keep all parts except the last one (the expiry)
    return '-'.join(parts[:-1])

def analyze_cross_expiry_positions(market_dicts):
    """
    market_dicts: list of dicts with keys 'token', 'market_name', 'positions_df'
    Returns: dict with base_token -> DataFrame of users with positions in multiple markets.
    """
    # Group by base token
    base_token_dict = {}
    for m in market_dicts:
        token = m['token']
        base = get_base_token(token)
        expiry = parse_expiry_from_token(token)
        if base not in base_token_dict:
            base_token_dict[base] = []
        base_token_dict[base].append({
            'token': token,
            'expiry': expiry,
            'market_name': m['market_name'],
            'positions_df': m['positions_df'].copy()
        })
    
    results = {}
    for base, markets in base_token_dict.items():
        # Sort markets by expiry (earliest first)
        markets.sort(key=lambda x: x['expiry'])
        # For each user, collect positions across markets
        user_positions = {}
        for m in markets:
            df = m['positions_df']
            for _, row in df.iterrows():
                user = row['user_address']
                if user not in user_positions:
                    user_positions[user] = []
                user_positions[user].append({
                    'expiry': m['expiry'],
                    'market_name': m['market_name'],
                    'opening_date': row['opening_date'],
                    'closing_date': row['closing_date'],
                    'max_debt': row['max_debt'],
                    'position_length_days': row['position_length_days'],
                    'days_to_expiry_after_close': row['days_to_expiry_after_close'],
                })
        # Keep only users with positions in more than one market
        multi_market_users = {u: pos for u, pos in user_positions.items() if len(pos) > 1}
        if multi_market_users:
            # Create a DataFrame for easier printing
            records = []
            for user, positions in multi_market_users.items():
                for pos in positions:
                    records.append({
                        'user_address': user,
                        'expiry': pos['expiry'],
                        'market_name': pos['market_name'],
                        'opening_date': pos['opening_date'],
                        'closing_date': pos['closing_date'],
                        'max_debt': pos['max_debt'],
                        'position_length_days': pos['position_length_days'],
                        'days_to_expiry_after_close': pos['days_to_expiry_after_close'],
                    })
            results[base] = pd.DataFrame(records).sort_values(['user_address', 'expiry'])
    
    return results

dd = analyze_cross_expiry_positions(all_markets_position)
for base, df in dd.items():
    print(f"\nBase token: {base}, n markets {df['market_name'].nunique()}")
    df['user_max_debt'] = df.groupby('user_address')['max_debt'].transform('max')

    # Sort by user_max_debt descending, then by expiry
    df_sorted = df.sort_values(['user_max_debt', 'expiry'], ascending=[False, True])

    # Drop the helper column
    df_sorted = df_sorted.drop(columns=['user_max_debt'])

    # Print
    print(df_sorted.to_string(index=False))

Base token: PT-slvlUSD, n markets 2
                              user_address     expiry                   market_name        opening_date        closing_date     max_debt  position_length_days  days_to_expiry_after_close
0xC28e8f073439800dF7A4934d198E1966B4Dd8A25 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-04-08 07:03:59 2025-05-29 07:03:59 6.397240e+06             51.000000                   -0.419433
0xC28e8f073439800dF7A4934d198E1966B4Dd8A25 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-05-29 06:38:47 2025-07-21 03:38:47 1.019801e+06             52.875000                   65.723067
0xFbbF1826Aba90704A2167D2EB4A7a9D83A8DE9c7 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-04-22 17:16:23 2025-05-29 21:16:23 6.395783e+06             37.166667                   -1.011377
0xFbbF1826Aba90704A2167D2EB4A7a9D83A8DE9c7 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-05-21 20:47:47 2025-07-19 23:47:47 1.137468e+06             59.125000                   66.883484
0x37829FE9b8e67B8267C2058b9459f524b9E3ca5d 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-05-13 15:09:47 2025-05-13 16:09:47 1.424612e+06              0.041667                   15.201539
0x37829FE9b8e67B8267C2058b9459f524b9E3ca5d 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-05-30 19:00:23 2025-05-31 14:00:23 2.999505e+05              0.791667                  116.291400
0x247c7B87bfa5c6f1638f83FB988f03b036c0Dc55 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-04-18 06:00:35 2025-06-19 07:00:35 1.363125e+05             62.041667                  -21.417072
0x247c7B87bfa5c6f1638f83FB988f03b036c0Dc55 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-06-19 06:02:47 2025-10-21 00:02:47 1.390038e+05            123.750000                  -26.126933
0x7063d2BB154C640c5fDc81767C2cCD1b96132865 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-05-08 11:21:59 2025-05-29 15:21:59 8.999445e+04             21.166667                   -0.765266
0x7063d2BB154C640c5fDc81767C2cCD1b96132865 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-06-02 11:01:23 2025-09-04 10:01:23 7.721912e+04             93.958333                   20.457373
0xA4F6C5e4821F0Aa628065E0cFcA47d15741466Bd 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-04-25 22:25:47 2025-05-29 00:25:47 8.077000e+04             33.083333                   -0.142905
0xA4F6C5e4821F0Aa628065E0cFcA47d15741466Bd 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-05-28 23:48:35 2025-07-09 00:48:35 8.071569e+04             41.041667                   77.841262
0x21ec97e963176eFDAE208495Db173B92a02905DF 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-04-15 13:38:11 2025-04-25 12:38:11 6.025281e+04              9.958333                   33.348484
0x21ec97e963176eFDAE208495Db173B92a02905DF 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-06-23 03:10:23 2025-09-07 19:10:23 6.008630e+04             76.666667                   17.076123
0x4623c7E299e90F2C6DeF8508746C635Bc17f7CDa 2025-05-29 eth_PT-slvlUSD-29MAY2025_usdc 2025-04-26 01:50:35 2025-05-20 01:50:35 1.049964e+04             24.000000                    8.798206
0x4623c7E299e90F2C6DeF8508746C635Bc17f7CDa 2025-09-25 eth_PT-slvlUSD-25SEP2025_usdc 2025-05-28 00:41:47 2025-07-02 02:41:47 1.305338e+04             35.083333                   84.762650

Base token: PT-USDe, n markets 7
                              user_address     expiry                market_name        opening_date        closing_date     max_debt  position_length_days  days_to_expiry_after_close
0xDbc652411605f8bB8969136923aa039c79989482 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-26 02:35:47 2025-09-13 19:35:47 7.992265e+07             18.708333                   11.058484
0xDbc652411605f8bB8969136923aa039c79989482 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-22 18:18:47 2025-09-13 19:18:47 6.678592e+07             22.041667                   11.070289
0xDbc652411605f8bB8969136923aa039c79989482 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-13 18:21:59 2025-09-18 12:21:59 1.127210e+08              4.750000                   69.359734
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-07-31  eth_PT-USDe-31JUL2025_dai 2025-06-07 13:34:23 2025-06-08 16:34:23 1.948563e+06              1.125000                   52.184456
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-21 20:30:23 2025-09-23 20:30:23 3.513272e+07             33.000000                    1.020567
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-21 20:54:35 2025-09-23 17:54:35 9.521688e+06             32.875000                    1.128762
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-09 08:05:23 2025-09-23 18:05:23 6.122648e+07             45.416667                    1.121262
0xd93814273b33DD33B32cD345225CfB65DEB048Dd 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-19 18:30:11 2025-08-23 19:30:11 2.219358e+06              4.041667                   32.062373
0xd93814273b33DD33B32cD345225CfB65DEB048Dd 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-12 19:22:47 2025-08-24 18:22:47 5.649402e+07             11.958333                   31.109178
0xd93814273b33DD33B32cD345225CfB65DEB048Dd 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-12 19:06:47 2025-09-18 21:06:47 5.458307e+07              6.083333                   68.995289
0xDe6b2a06407575B98724818445178C1f5fD53361 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-23 09:51:11 2025-09-25 04:51:11 4.680000e+07             32.791667                   -0.327211
0xDe6b2a06407575B98724818445178C1f5fD53361 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-01 22:55:59 2025-08-09 08:55:59 1.999358e+06              7.416667                   46.502789
0xDe6b2a06407575B98724818445178C1f5fD53361 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-10 13:32:23 2025-08-13 15:32:23 1.059795e+07              3.083333                   42.227512
0x1fc75ad0511DDC3A23B9583BA1C285b8292FAEd5 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-15 03:51:59 2025-09-25 01:51:59 4.399859e+07              9.916667                   -0.202766
0x1fc75ad0511DDC3A23B9583BA1C285b8292FAEd5 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-16 01:37:23 2025-09-25 01:37:23 2.399162e+07              9.000000                   -0.192627
0x1fc75ad0511DDC3A23B9583BA1C285b8292FAEd5 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-16 16:57:59 2025-09-25 03:57:59 3.499013e+06              8.458333                   62.709734
0x051Ef87C542Ec5cA717AA19210B2657598a57319 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-13 12:53:35 2025-09-19 09:53:35 1.943681e+07              5.875000                    5.462789
0x051Ef87C542Ec5cA717AA19210B2657598a57319 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-13 13:45:23 2025-10-04 10:45:23 3.978531e+07             20.875000                   53.426817
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-07-31  eth_PT-USDe-31JUL2025_dai 2025-03-27 05:59:35 2025-03-27 15:59:35 3.048957e+06              0.416667                  125.208623
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-22 00:43:23 2025-08-23 12:43:23 2.300000e+06              1.500000                   32.344873
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-22 00:18:47 2025-08-22 11:18:47 2.299494e+06              0.458333                   33.403623
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-21 04:11:35 2025-09-22 14:11:35 3.433246e+07             32.416667                    2.283623
0x9fb1750Da6266a05601855bb62767eBC742707B1 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-03 20:40:35 2025-09-14 06:40:35 2.628293e+07             10.416667                   10.596817
0x9fb1750Da6266a05601855bb62767eBC742707B1 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-09 21:00:47 2025-09-14 07:00:47 8.848301e+06              4.416667                   10.582789
0x1be45feF92C4E2538fEcd150757Ed62b7B3757D7 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-23 10:18:59 2025-09-13 18:18:59 9.998131e+06             21.333333                   11.111817
0x1be45feF92C4E2538fEcd150757Ed62b7B3757D7 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-13 17:43:11 2025-09-18 14:43:11 1.563149e+07              4.875000                   69.261678
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-03-27  eth_PT-USDe-27MAR2025_dai 2024-12-15 21:57:23 2025-02-11 08:57:23 8.439555e+06             57.458333                   43.501817
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-30 12:01:47 2025-09-25 05:01:47 1.539747e+07             25.708333                   -0.334572
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-15 17:23:47 2025-08-25 04:23:47 1.068111e+05              9.458333                   30.691817
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-10 20:26:11 2025-09-20 01:26:11 1.075213e+07              9.208333                   67.815150
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-11-27 eth_PT-USDe-27NOV2025_usdc 2025-09-17 22:21:35 2025-09-18 09:21:35 1.169657e+06              0.458333                   69.485012
0x869C98f94C1A15118Ca10cd86F74B1A3550Cdd29 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-05 17:13:11 2025-09-22 12:13:11 5.995140e+06             16.791667                    2.365845
0x869C98f94C1A15118Ca10cd86F74B1A3550Cdd29 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-20 06:51:47 2025-09-23 06:51:47 1.449716e+07             34.000000                    1.589039
0x901431E0303426D5f28180f0fb2C616e97D3Be71 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-20 11:34:11 2025-09-23 13:34:11 1.414887e+07             34.083333                    1.309595
0x901431E0303426D5f28180f0fb2C616e97D3Be71 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-16 21:55:35 2025-08-20 20:55:35 6.668536e+06              3.958333                   35.003067
0x901431E0303426D5f28180f0fb2C616e97D3Be71 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-11 15:06:35 2025-09-13 17:06:35 1.799390e+05              2.083333                   74.162095
0x14FAa112a14b70328D2cA17102aAfE398F0c369c 2025-03-27  eth_PT-USDe-27MAR2025_dai 2025-01-04 06:07:11 2025-03-27 00:07:11 1.240169e+07             81.750000                   -0.129988
0x14FAa112a14b70328D2cA17102aAfE398F0c369c 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-12 04:42:11 2025-09-27 03:42:11 1.483549e+06             14.958333                   60.720706
0xF8A675Ea246339EA86280770e0fD6e83f53BB2b5 2025-03-27  eth_PT-USDe-27MAR2025_dai 2024-12-30 04:20:35 2025-03-23 03:20:35 9.656312e+06             82.958333                    3.735706
0xF8A675Ea246339EA86280770e0fD6e83f53BB2b5 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-13 14:43:59 2025-09-18 00:43:59 5.042290e+05              4.416667                    6.844456
0x1510a8c2792e75aa5d8DC6159F0C2e56C8B178e8 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-06 06:13:59 2025-09-20 07:13:59 8.910000e+06             14.041667                    4.573623
0x1510a8c2792e75aa5d8DC6159F0C2e56C8B178e8 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-16 02:11:11 2025-09-06 07:11:11 2.649166e+06             21.208333                   18.575567
0x1510a8c2792e75aa5d8DC6159F0C2e56C8B178e8 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-23 05:51:35 2025-09-20 06:51:35 7.498522e+06             28.041667                    4.589178
0x424Ffe585300C61f7a92AFbA971315d0B15C529B 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-25 05:54:11 2025-09-23 15:54:11 8.714897e+06             29.416667                    1.212373
0x424Ffe585300C61f7a92AFbA971315d0B15C529B 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-13 23:11:35 2025-08-28 19:11:35 3.218457e+06             14.833333                   27.075289
0x424Ffe585300C61f7a92AFbA971315d0B15C529B 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 22:52:11 2025-08-22 11:52:11 2.335435e+06              8.541667                   33.380428
0x3F75C3932603A8ba54ad81277313D19C22635FF9 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-13 01:38:47 2025-09-25 01:38:47 1.873583e+06             43.000000                   -0.193600
0x3F75C3932603A8ba54ad81277313D19C22635FF9 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 09:27:23 2025-09-22 14:27:23 8.558322e+06             40.208333                    2.272650
0x3F02fF0eD87da901229B66965E694F5ca4102D87 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-06 05:56:59 2025-09-20 06:56:59 7.610000e+06             14.041667                    4.585428
0x3F02fF0eD87da901229B66965E694F5ca4102D87 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-29 12:35:35 2025-09-06 06:35:35 1.740000e+06              7.750000                   18.600289
0x3F02fF0eD87da901229B66965E694F5ca4102D87 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-24 13:20:23 2025-09-20 06:20:23 6.604685e+06             26.708333                    4.610845
0xA1f3cDAEC36bb391459277faB29d73A34626Bb96 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-08 15:26:35 2025-09-21 09:26:35 6.446558e+06             12.750000                    3.481539
0xA1f3cDAEC36bb391459277faB29d73A34626Bb96 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-09 03:23:23 2025-09-21 02:23:23 6.208628e+06             11.958333                    3.775428
0x3a55e304D9cF13E45Ead6BA3DabCcadD3a419356 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-27 19:47:11 2025-09-17 03:47:11 1.080000e+06             20.333333                    7.717234
0x3a55e304D9cF13E45Ead6BA3DabCcadD3a419356 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-02 21:09:59 2025-08-25 10:09:59 5.302610e+06             22.541667                   30.451400
0x16f037a3dDf53dA1b047A926E1833219F0a8E1FC 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 07:29:23 2025-08-14 05:29:23 4.319388e+05              0.916667                   41.646262
0x16f037a3dDf53dA1b047A926E1833219F0a8E1FC 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-10 01:31:11 2025-09-25 06:31:11 3.835535e+06             15.208333                   62.603345
0xC83645968AafCadcD1b6b399124EF4D18CB43f3A 2025-03-27  eth_PT-USDe-27MAR2025_dai 2025-01-04 16:47:11 2025-02-21 10:47:11 5.000000e+05             47.750000                   33.425567
0xC83645968AafCadcD1b6b399124EF4D18CB43f3A 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-15 02:30:11 2025-09-25 02:30:11 3.599298e+06             41.000000                   -0.229294
0x21C9cE0611541099583E4249bfB583606715a796 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-17 06:23:35 2025-09-16 09:23:35 5.820000e+05             30.125000                    8.483623
0x21C9cE0611541099583E4249bfB583606715a796 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-09 08:04:59 2025-09-16 10:04:59 3.531069e+06             38.083333                    8.454873
0x21C9cE0611541099583E4249bfB583606715a796 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 05:09:59 2025-08-25 20:09:59 7.549044e+05             12.625000                   30.034734
0x21C9cE0611541099583E4249bfB583606715a796 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-16 11:13:11 2025-09-25 13:13:11 6.546922e+05              9.083333                   62.324178
0x81bb45b5414b1C1cf7a8DD334c3a595aD090829d 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-28 17:19:59 2025-09-24 17:19:59 3.324628e+06             27.000000                    0.152789
0x81bb45b5414b1C1cf7a8DD334c3a595aD090829d 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-28 17:08:35 2025-09-24 18:08:35 8.538052e+05             27.041667                    0.119039
0x08E63b00B38eA99d745edF61FB653f8949aEA5e0 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-23 07:58:59 2025-09-24 14:58:59 3.100000e+06             32.291667                    0.250706
0x08E63b00B38eA99d745edF61FB653f8949aEA5e0 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-19 13:14:59 2025-08-23 09:14:59 3.079390e+06              3.833333                   32.489595
0x0EDD42c2888d9Ecd7fBc11C657354953f33eEf67 2025-07-31  eth_PT-USDe-31JUL2025_dai 2025-06-26 05:48:59 2025-07-02 01:48:59 4.289635e+05              5.833333                   28.799317
0x0EDD42c2888d9Ecd7fBc11C657354953f33eEf67 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-02 22:01:23 2025-09-22 12:01:23 2.975000e+06             50.583333                    2.374039
0xA7a4d86B692E5B4e0711a48184065f64A3ACe278 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-04 04:55:47 2025-08-13 12:55:47 2.150713e+06              9.333333                   42.336262
0xA7a4d86B692E5B4e0711a48184065f64A3ACe278 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-04 05:11:47 2025-08-13 18:11:47 2.871455e+06              9.541667                   42.116817
0x10510c13d916f32f101607d71B06D7F2E5551371 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-26 15:46:47 2025-09-23 15:46:47 2.772478e+06             28.000000                    1.217512
0x10510c13d916f32f101607d71B06D7F2E5551371 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-11 00:47:59 2025-08-11 04:47:59 6.476523e+04              0.166667                   44.675012
0xA7FB007EE39c1881a831a7e6295E5E92929CbDe2 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-22 07:18:59 2025-09-24 13:18:59 2.568704e+06              2.250000                    0.320150
0xA7FB007EE39c1881a831a7e6295E5E92929CbDe2 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-12 04:22:59 2025-09-02 02:22:59 8.008438e+05             20.916667                   22.775706
0x71F87A110ffF7678E309a1292c5A8B4cC5428A31 2025-03-27  eth_PT-USDe-27MAR2025_dai 2025-03-15 03:57:59 2025-03-25 01:57:59 2.389671e+06              9.916667                    1.793067
0x71F87A110ffF7678E309a1292c5A8B4cC5428A31 2025-07-31  eth_PT-USDe-31JUL2025_dai 2025-03-29 04:40:47 2025-04-01 05:40:47 2.834892e+05              3.041667                  120.638345
0xaADEA5a1DaB8FcC99FD58aE8524187D7516d9Be1 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-02 14:46:11 2025-09-25 01:46:11 3.447623e+05             22.458333                   -0.198738
0xaADEA5a1DaB8FcC99FD58aE8524187D7516d9Be1 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-15 18:25:11 2025-09-25 01:25:11 1.199930e+06             40.291667                   -0.184155
0xaADEA5a1DaB8FcC99FD58aE8524187D7516d9Be1 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-14 01:13:35 2025-09-25 01:13:35 2.337876e+06             42.000000                   -0.176100
0x6C02b50e8044aF30F136d5Dd49C86BaF927Ca69E 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-12 15:09:35 2025-09-24 18:09:35 2.152128e+06             43.125000                    0.118345
0x6C02b50e8044aF30F136d5Dd49C86BaF927Ca69E 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-10 07:51:35 2025-09-24 17:51:35 1.697292e+06             45.416667                    0.130845
0x47669d1cD7091Fe1DAFE741fE3528fDf559B8A67 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-08 08:33:23 2025-08-11 07:33:23 1.200000e+06              2.958333                   44.560150
0x47669d1cD7091Fe1DAFE741fE3528fDf559B8A67 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-08 10:35:47 2025-08-11 07:35:47 2.119510e+06              2.875000                   44.558484
0xA4fc1516a78Bb510b41c18393d113A0A5e7387Ab 2025-03-27  eth_PT-USDe-27MAR2025_dai 2025-01-16 21:31:47 2025-01-17 00:31:47 9.999980e+05              0.125000                   68.852928
0xA4fc1516a78Bb510b41c18393d113A0A5e7387Ab 2025-07-31  eth_PT-USDe-31JUL2025_dai 2025-05-05 22:35:11 2025-05-07 14:35:11 4.499194e+05              1.666667                   84.267234
0xA4fc1516a78Bb510b41c18393d113A0A5e7387Ab 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-31 14:19:59 2025-09-02 04:19:59 2.000000e+06              1.583333                   22.694456
0xbDcB41C73274EcEDED3E9ADE6E212d062fb4C24F 2025-03-27  eth_PT-USDe-27MAR2025_dai 2025-01-21 10:40:47 2025-02-23 14:40:47 9.997270e-01             33.166667                   31.263345
0xbDcB41C73274EcEDED3E9ADE6E212d062fb4C24F 2025-07-31  eth_PT-USDe-31JUL2025_dai 2025-04-27 05:46:47 2025-05-31 09:46:47 1.729529e+06             34.166667                   60.467512
0x08Fce4e6F5Eff52d04df42b4D90d6e6447f26b80 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-22 06:00:23 2025-08-23 09:00:23 2.937876e+05              1.125000                   32.499734

In [8]:
for base, df in dd.items():
    print(f"\nBase token: {base}, n markets {df['market_name'].nunique()}")
    same_expirity_users = df.groupby(["user_address", 'expiry'])['market_name'].count()
    same_expirity_users = same_expirity_users[same_expirity_users>1].reset_index()
    df = df[df['user_address'].isin(same_expirity_users['user_address']) & df['expiry'].isin(same_expirity_users['expiry'])]
    df['user_max_debt'] = df.groupby('user_address')['max_debt'].transform('max')

    # Sort by user_max_debt descending, then by expiry
    df_sorted = df.sort_values(['user_max_debt', 'expiry'], ascending=[False, True])

    # Drop the helper column
    df_sorted = df_sorted.drop(columns=['user_max_debt'])

    # Print
    print(df_sorted.to_string(index=False))

Base token: PT-slvlUSD, n markets 2
Empty DataFrame
Columns: [user_address, expiry, market_name, opening_date, closing_date, max_debt, position_length_days, days_to_expiry_after_close]
Index: []

Base token: PT-USDe, n markets 7
                              user_address     expiry                market_name        opening_date        closing_date     max_debt  position_length_days  days_to_expiry_after_close
0xDbc652411605f8bB8969136923aa039c79989482 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-26 02:35:47 2025-09-13 19:35:47 7.992265e+07             18.708333                   11.058484
0xDbc652411605f8bB8969136923aa039c79989482 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-22 18:18:47 2025-09-13 19:18:47 6.678592e+07             22.041667                   11.070289
0xDbc652411605f8bB8969136923aa039c79989482 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-13 18:21:59 2025-09-18 12:21:59 1.127210e+08              4.750000                   69.359734
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-21 20:30:23 2025-09-23 20:30:23 3.513272e+07             33.000000                    1.020567
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-21 20:54:35 2025-09-23 17:54:35 9.521688e+06             32.875000                    1.128762
0xf2085a1521D11396FD182C7a5Fb2622f74cf1De6 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-09 08:05:23 2025-09-23 18:05:23 6.122648e+07             45.416667                    1.121262
0xd93814273b33DD33B32cD345225CfB65DEB048Dd 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-19 18:30:11 2025-08-23 19:30:11 2.219358e+06              4.041667                   32.062373
0xd93814273b33DD33B32cD345225CfB65DEB048Dd 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-12 19:22:47 2025-08-24 18:22:47 5.649402e+07             11.958333                   31.109178
0xd93814273b33DD33B32cD345225CfB65DEB048Dd 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-12 19:06:47 2025-09-18 21:06:47 5.458307e+07              6.083333                   68.995289
0xDe6b2a06407575B98724818445178C1f5fD53361 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-23 09:51:11 2025-09-25 04:51:11 4.680000e+07             32.791667                   -0.327211
0xDe6b2a06407575B98724818445178C1f5fD53361 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-01 22:55:59 2025-08-09 08:55:59 1.999358e+06              7.416667                   46.502789
0xDe6b2a06407575B98724818445178C1f5fD53361 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-10 13:32:23 2025-08-13 15:32:23 1.059795e+07              3.083333                   42.227512
0x1fc75ad0511DDC3A23B9583BA1C285b8292FAEd5 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-15 03:51:59 2025-09-25 01:51:59 4.399859e+07              9.916667                   -0.202766
0x1fc75ad0511DDC3A23B9583BA1C285b8292FAEd5 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-16 01:37:23 2025-09-25 01:37:23 2.399162e+07              9.000000                   -0.192627
0x1fc75ad0511DDC3A23B9583BA1C285b8292FAEd5 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-16 16:57:59 2025-09-25 03:57:59 3.499013e+06              8.458333                   62.709734
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-22 00:43:23 2025-08-23 12:43:23 2.300000e+06              1.500000                   32.344873
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-22 00:18:47 2025-08-22 11:18:47 2.299494e+06              0.458333                   33.403623
0xCCeE77e74C4466DF0dA0ec85F2D3505956fD6Fa7 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-21 04:11:35 2025-09-22 14:11:35 3.433246e+07             32.416667                    2.283623
0x9fb1750Da6266a05601855bb62767eBC742707B1 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-03 20:40:35 2025-09-14 06:40:35 2.628293e+07             10.416667                   10.596817
0x9fb1750Da6266a05601855bb62767eBC742707B1 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-09 21:00:47 2025-09-14 07:00:47 8.848301e+06              4.416667                   10.582789
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-30 12:01:47 2025-09-25 05:01:47 1.539747e+07             25.708333                   -0.334572
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-15 17:23:47 2025-08-25 04:23:47 1.068111e+05              9.458333                   30.691817
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-10 20:26:11 2025-09-20 01:26:11 1.075213e+07              9.208333                   67.815150
0xc6dD9976066F3364b4D6A72cD4F1fA0468327Aa7 2025-11-27 eth_PT-USDe-27NOV2025_usdc 2025-09-17 22:21:35 2025-09-18 09:21:35 1.169657e+06              0.458333                   69.485012
0x869C98f94C1A15118Ca10cd86F74B1A3550Cdd29 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-05 17:13:11 2025-09-22 12:13:11 5.995140e+06             16.791667                    2.365845
0x869C98f94C1A15118Ca10cd86F74B1A3550Cdd29 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-20 06:51:47 2025-09-23 06:51:47 1.449716e+07             34.000000                    1.589039
0x901431E0303426D5f28180f0fb2C616e97D3Be71 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-20 11:34:11 2025-09-23 13:34:11 1.414887e+07             34.083333                    1.309595
0x901431E0303426D5f28180f0fb2C616e97D3Be71 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-16 21:55:35 2025-08-20 20:55:35 6.668536e+06              3.958333                   35.003067
0x901431E0303426D5f28180f0fb2C616e97D3Be71 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-11 15:06:35 2025-09-13 17:06:35 1.799390e+05              2.083333                   74.162095
0x1510a8c2792e75aa5d8DC6159F0C2e56C8B178e8 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-06 06:13:59 2025-09-20 07:13:59 8.910000e+06             14.041667                    4.573623
0x1510a8c2792e75aa5d8DC6159F0C2e56C8B178e8 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-16 02:11:11 2025-09-06 07:11:11 2.649166e+06             21.208333                   18.575567
0x1510a8c2792e75aa5d8DC6159F0C2e56C8B178e8 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-23 05:51:35 2025-09-20 06:51:35 7.498522e+06             28.041667                    4.589178
0x424Ffe585300C61f7a92AFbA971315d0B15C529B 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-25 05:54:11 2025-09-23 15:54:11 8.714897e+06             29.416667                    1.212373
0x424Ffe585300C61f7a92AFbA971315d0B15C529B 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-13 23:11:35 2025-08-28 19:11:35 3.218457e+06             14.833333                   27.075289
0x424Ffe585300C61f7a92AFbA971315d0B15C529B 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 22:52:11 2025-08-22 11:52:11 2.335435e+06              8.541667                   33.380428
0x3F75C3932603A8ba54ad81277313D19C22635FF9 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-13 01:38:47 2025-09-25 01:38:47 1.873583e+06             43.000000                   -0.193600
0x3F75C3932603A8ba54ad81277313D19C22635FF9 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 09:27:23 2025-09-22 14:27:23 8.558322e+06             40.208333                    2.272650
0x3F02fF0eD87da901229B66965E694F5ca4102D87 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-06 05:56:59 2025-09-20 06:56:59 7.610000e+06             14.041667                    4.585428
0x3F02fF0eD87da901229B66965E694F5ca4102D87 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-29 12:35:35 2025-09-06 06:35:35 1.740000e+06              7.750000                   18.600289
0x3F02fF0eD87da901229B66965E694F5ca4102D87 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-24 13:20:23 2025-09-20 06:20:23 6.604685e+06             26.708333                    4.610845
0xA1f3cDAEC36bb391459277faB29d73A34626Bb96 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-08 15:26:35 2025-09-21 09:26:35 6.446558e+06             12.750000                    3.481539
0xA1f3cDAEC36bb391459277faB29d73A34626Bb96 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-09 03:23:23 2025-09-21 02:23:23 6.208628e+06             11.958333                    3.775428
0x3a55e304D9cF13E45Ead6BA3DabCcadD3a419356 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-27 19:47:11 2025-09-17 03:47:11 1.080000e+06             20.333333                    7.717234
0x3a55e304D9cF13E45Ead6BA3DabCcadD3a419356 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-02 21:09:59 2025-08-25 10:09:59 5.302610e+06             22.541667                   30.451400
0x21C9cE0611541099583E4249bfB583606715a796 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-17 06:23:35 2025-09-16 09:23:35 5.820000e+05             30.125000                    8.483623
0x21C9cE0611541099583E4249bfB583606715a796 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-09 08:04:59 2025-09-16 10:04:59 3.531069e+06             38.083333                    8.454873
0x21C9cE0611541099583E4249bfB583606715a796 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-13 05:09:59 2025-08-25 20:09:59 7.549044e+05             12.625000                   30.034734
0x21C9cE0611541099583E4249bfB583606715a796 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-16 11:13:11 2025-09-25 13:13:11 6.546922e+05              9.083333                   62.324178
0x81bb45b5414b1C1cf7a8DD334c3a595aD090829d 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-28 17:19:59 2025-09-24 17:19:59 3.324628e+06             27.000000                    0.152789
0x81bb45b5414b1C1cf7a8DD334c3a595aD090829d 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-28 17:08:35 2025-09-24 18:08:35 8.538052e+05             27.041667                    0.119039
0x08E63b00B38eA99d745edF61FB653f8949aEA5e0 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-23 07:58:59 2025-09-24 14:58:59 3.100000e+06             32.291667                    0.250706
0x08E63b00B38eA99d745edF61FB653f8949aEA5e0 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-19 13:14:59 2025-08-23 09:14:59 3.079390e+06              3.833333                   32.489595
0xA7a4d86B692E5B4e0711a48184065f64A3ACe278 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-04 04:55:47 2025-08-13 12:55:47 2.150713e+06              9.333333                   42.336262
0xA7a4d86B692E5B4e0711a48184065f64A3ACe278 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-04 05:11:47 2025-08-13 18:11:47 2.871455e+06              9.541667                   42.116817
0x10510c13d916f32f101607d71B06D7F2E5551371 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-26 15:46:47 2025-09-23 15:46:47 2.772478e+06             28.000000                    1.217512
0x10510c13d916f32f101607d71B06D7F2E5551371 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-11 00:47:59 2025-08-11 04:47:59 6.476523e+04              0.166667                   44.675012
0xA7FB007EE39c1881a831a7e6295E5E92929CbDe2 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-22 07:18:59 2025-09-24 13:18:59 2.568704e+06              2.250000                    0.320150
0xA7FB007EE39c1881a831a7e6295E5E92929CbDe2 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-12 04:22:59 2025-09-02 02:22:59 8.008438e+05             20.916667                   22.775706
0xaADEA5a1DaB8FcC99FD58aE8524187D7516d9Be1 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-02 14:46:11 2025-09-25 01:46:11 3.447623e+05             22.458333                   -0.198738
0xaADEA5a1DaB8FcC99FD58aE8524187D7516d9Be1 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-15 18:25:11 2025-09-25 01:25:11 1.199930e+06             40.291667                   -0.184155
0xaADEA5a1DaB8FcC99FD58aE8524187D7516d9Be1 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-14 01:13:35 2025-09-25 01:13:35 2.337876e+06             42.000000                   -0.176100
0x6C02b50e8044aF30F136d5Dd49C86BaF927Ca69E 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-12 15:09:35 2025-09-24 18:09:35 2.152128e+06             43.125000                    0.118345
0x6C02b50e8044aF30F136d5Dd49C86BaF927Ca69E 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-10 07:51:35 2025-09-24 17:51:35 1.697292e+06             45.416667                    0.130845
0x47669d1cD7091Fe1DAFE741fE3528fDf559B8A67 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-08 08:33:23 2025-08-11 07:33:23 1.200000e+06              2.958333                   44.560150
0x47669d1cD7091Fe1DAFE741fE3528fDf559B8A67 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-08 10:35:47 2025-08-11 07:35:47 2.119510e+06              2.875000                   44.558484
0x08Fce4e6F5Eff52d04df42b4D90d6e6447f26b80 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-22 06:00:23 2025-08-23 09:00:23 2.937876e+05              1.125000                   32.499734
0x08Fce4e6F5Eff52d04df42b4D90d6e6447f26b80 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-22 02:44:59 2025-09-26 03:44:59 1.688367e+06             35.041667                   -1.281238
0xdB5f00B55723eF190A041F9f3f7DbD20086Bd79c 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-08 14:44:59 2025-09-10 10:44:59 3.059575e+05              1.833333                   14.427095
0xdB5f00B55723eF190A041F9f3f7DbD20086Bd79c 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-09-08 11:52:11 2025-09-22 10:52:11 1.423374e+06             13.958333                    2.422095
0xA4b93d80cEeaF2960927BB719092A1529979Ac93 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-06 12:36:59 2025-09-25 19:36:59 1.160657e+06             19.291667                   -0.942350
0xA4b93d80cEeaF2960927BB719092A1529979Ac93 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-05 22:24:35 2025-09-26 21:24:35 1.301903e+06             51.958333                   -2.017072
0xEB53FD8C797112C569dcd15E75C26386a2378AA8 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-14 07:52:35 2025-09-18 03:52:35 8.153097e+05              3.833333                    6.713484
0xEB53FD8C797112C569dcd15E75C26386a2378AA8 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-08 04:27:35 2025-09-18 03:27:35 1.288734e+05              9.958333                    6.730845
0xEB53FD8C797112C569dcd15E75C26386a2378AA8 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-18 03:23:35 2025-09-25 02:23:35 1.463308e+05              6.958333                   62.775289
0xB3F8A1885bb8C1afFe4980d8926132A0C3A318d5 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-14 09:52:47 2025-09-26 08:52:47 2.450000e+05             42.958333                   -1.494988
0xB3F8A1885bb8C1afFe4980d8926132A0C3A318d5 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-11 16:39:11 2025-09-07 10:39:11 7.928335e+05             26.750000                   17.431123
0x1a0C96eF4c775697D9ba9A99124dF73536Fd3866 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-09-10 10:46:59 2025-09-24 02:46:59 7.690000e+05             13.666667                    0.759039
0x1a0C96eF4c775697D9ba9A99124dF73536Fd3866 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-05 13:47:35 2025-08-06 06:47:35 1.617563e+05              0.708333                   49.591956
0x7a20bF10659202afdA190AeDA36fFC5c3746fEaE 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-20 09:30:23 2025-08-21 05:30:23 2.638000e+05              0.833333                   34.645567
0x7a20bF10659202afdA190AeDA36fFC5c3746fEaE 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-02 12:01:35 2025-08-29 12:01:35 6.829925e+05             27.000000                   26.373900
0xb5591c65890332Ab997855d4F59641c787583315 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-29 23:27:23 2025-09-24 02:27:23 5.344129e+05             25.125000                    0.772650
0xb5591c65890332Ab997855d4F59641c787583315 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-07-31 04:49:23 2025-08-07 05:49:23 3.214000e+05              7.041667                   48.632373
0x5c41796cbC77C9cB3f8b8F012c626c59cB39E03F 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-14 14:51:35 2025-09-21 19:51:35 5.151064e+05             38.208333                    3.047512
0x5c41796cbC77C9cB3f8b8F012c626c59cB39E03F 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-10 18:46:23 2025-08-14 14:46:23 2.847679e+05              3.833333                   41.259456
0x551dAf3290401Ba45Fb5a30bBCD57e646C16D7f8 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-29 06:19:35 2025-09-11 00:19:35 3.494156e+05             12.750000                   13.861400
0x551dAf3290401Ba45Fb5a30bBCD57e646C16D7f8 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-28 15:51:35 2025-08-29 08:51:35 1.177023e+05              0.708333                   26.505845
0x551dAf3290401Ba45Fb5a30bBCD57e646C16D7f8 2025-11-27 eth_PT-USDe-27NOV2025_usds 2025-09-10 23:17:35 2025-09-18 12:17:35 4.611635e+05              7.541667                   69.362789
0x51Cd245699780aD2be18fDF254d6c519adF971a6 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-05 02:44:47 2025-09-25 03:44:47 2.955000e+05             20.041667                   -0.281100
0x51Cd245699780aD2be18fDF254d6c519adF971a6 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-08 07:08:47 2025-08-22 04:08:47 4.499109e+05             13.875000                   33.702234
0xc415cD5e1B2Ce7ed75a425934326DeAde5713b57 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-20 12:23:11 2025-09-23 09:23:11 4.244212e+05              2.875000                    1.483900
0xc415cD5e1B2Ce7ed75a425934326DeAde5713b57 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-09-20 12:14:47 2025-09-23 09:14:47 1.604850e+05              2.875000                    1.489734
0x24a1A76F8d573c9460A497A1103eB43FE59AA46D 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-11 13:36:59 2025-08-23 11:36:59 4.091497e+05             11.916667                   32.390984
0x24a1A76F8d573c9460A497A1103eB43FE59AA46D 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-14 12:33:59 2025-08-14 14:33:59 1.809658e+04              0.083333                   41.268067
0xb8e0edD0d0cb1721FD367Dd21a82542204Fa1a20 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-31 15:58:35 2025-09-10 06:58:35 3.919863e+05              9.625000                   14.584317
0xb8e0edD0d0cb1721FD367Dd21a82542204Fa1a20 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-09-13 14:48:11 2025-09-22 02:48:11 1.316763e+05              8.500000                    2.758206
0x01c2f22754E1C2cc64A18Ba6162E5C7d417ffF7f 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-02 04:37:59 2025-09-25 00:37:59 3.826885e+05             22.833333                   -0.151377
0x01c2f22754E1C2cc64A18Ba6162E5C7d417ffF7f 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-17 06:25:47 2025-08-17 16:25:47 2.502500e+05              0.416667                   38.190428
0x01c2f22754E1C2cc64A18Ba6162E5C7d417ffF7f 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-23 03:35:11 2025-08-23 09:35:11 2.499508e+05              0.250000                   32.475567
0x8E785B15446Dbe320AE3D57559a959C8255001E2 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-11 13:26:11 2025-09-25 18:26:11 3.094122e+05             45.208333                   -0.893183
0x8E785B15446Dbe320AE3D57559a959C8255001E2 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-11 10:00:59 2025-09-25 18:00:59 3.562351e+05             45.333333                   -0.875683
0x8F21994745D88E11045c26d3D4bD519B5fed925D 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-09-02 03:07:47 2025-09-03 13:07:47 3.426356e+05              1.416667                   21.327928
0x8F21994745D88E11045c26d3D4bD519B5fed925D 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-08-10 01:45:23 2025-08-11 03:45:23 2.283961e+05              1.083333                   44.718484
0x6B9410449200579CF66e641dF17d681f71537a7E 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-29 15:14:47 2025-09-09 17:14:47 2.845013e+05             11.083333                   15.156400
0x6B9410449200579CF66e641dF17d681f71537a7E 2025-09-25 eth_PT-USDe-25SEP2025_usdt 2025-07-30 22:57:35 2025-08-02 16:57:35 1.049964e+05              2.750000                   53.168345
0x6B9410449200579CF66e641dF17d681f71537a7E 2025-09-25 eth_PT-USDe-25SEP2025_usdc 2025-08-02 16:12:35 2025-08-06 07:12:35 2.551727e+05              3.625000                   49.574595
0xCC050cAF8236DeB42820b6df1597934fa3762348 2025-09-25  eth_PT-USDe-25SEP2025_dai 2025-08-19 16:03:59 2025-09-04 18:03:59 2.009618e+05             16.083333                   20.122234

/var/folders/hj/pbs977kd43s6n1l9z3mxrj200000gn/T/ipykernel_16396/1928309420.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_max_debt'] = df.groupby('user_address')['max_debt'].transform('max')
/var/folders/hj/pbs977kd43s6n1l9z3mxrj200000gn/T/ipykernel_16396/1928309420.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_max_debt'] = df.groupby('user_address')['max_debt'].transform('max')

In [60]:
for i in range(len(all_markets_position)):
    if all_markets_position[i]['raw_df']['implied_apy'].max() == 0:
        print(all_markets_position[i]['market_name'])

In [29]:
from collections import defaultdict
base_to_index = defaultdict(list)
market2index = {}
for i in range(len(all_markets_position)):
    market2index[all_markets_position[i]['market_name']] = i
    base_to_index[get_base_token(all_markets_position[i]['token'])].append(i)
base_to_index
market2index

{'eth_PT-syrupUSDC-28AUG2025_usdc': 0,
 'eth_PT-slvlUSD-25SEP2025_usdc': 1,
 'eth_PT-USDe-27NOV2025_usds': 2,
 'eth_PT-USDe-25SEP2025_dai': 3,
 'eth_PT-syrupUSDC-30OCT2025_usdc': 4,
 'eth_PT-stcUSD-23JUL2026_usdc': 5,
 'eth_PT-USDe-27NOV2025_usdc': 6,
 'eth_PT-wstUSR-27MAR2025_usr': 7,
 'eth_PT-sNUSD-5MAR2026_usdc': 8,
 'eth_PT-USD0++-31OCT2024_usdc': 9,
 'eth_PT-USDe-31JUL2025_dai': 10,
 'eth_PT-USDe-25SEP2025_usdt': 11,
 'eth_PT-USDe-25SEP2025_usdc': 12,
 'eth_PT-wstUSR-27MAR2025_usdc': 13,
 'eth_PT-slvlUSD-29MAY2025_usdc': 14,
 'eth_PT-mHYPER-20NOV2025_usdc': 15,
 'eth_PT-reUSD-25JUN2026_usdc': 16,
 'eth_PT-reUSD-18DEC2025_usdc': 17,
 'eth_PT-RLP-4SEP2025_usdc': 18,
 'eth_PT-csUSDL-31JUL2025_usdc': 19,
 'eth_PT-wstUSR-25SEP2025_usdc': 20,
 'eth_PT-stcUSD-29JAN2026_usdc': 21,
 'eth_PT-lvlUSD-29MAY2025_usdc': 22,
 'eth_PT-USR-29MAY2025_usdc': 23,
 'eth_PT-USDe-27MAR2025_dai': 24,
 'eth_PT-USD0++-27MAR2025_usdc': 25}

In [26]:
all_markets_position[0]['market_df']

,timestamp,datetime,total_supply,total_borrow,utilization,borrow_rate,supply_rate,volatility_1h,drawdown_1h,volatility_6h,drawdown_6h,collateral_price,loan_asset_price,avg_health_factor,borrow_rate_rolling,supply_rate_rolling,asset_price,base_apy,implied_apy,underlying_apy
0,1747184400,2025-05-14 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.976228,0.102539,0.090325,0.069096
1,1747188000,2025-05-14 02:00:00,1.000000,1.000000,1.000000,0.159420,0.159420,0,0,0.000116,0.0,0.975220,1.000000,1.829326,0.079710,0.079710,0.975220,0.102181,0.090325,0.069088
2,1747191600,2025-05-14 03:00:00,1.000000,1.000000,1.000000,0.159420,0.159420,0,0,0.000116,0.0,0.975220,1.000000,1.829326,0.106280,0.106280,0.975229,0.102219,0.090325,0.069081
3,1747195200,2025-05-14 04:00:00,1.000000,1.000000,1.000000,0.159420,0.159420,0,0,0.000116,0.0,0.975220,1.000000,1.829326,0.119565,0.119565,0.975229,0.102236,0.090325,0.069073
4,1747198800,2025-05-14 05:00:00,1.000000,1.000000,1.000000,0.159420,0.159420,0,0,0.000116,0.0,0.975220,1.000000,1.829326,0.127536,0.127536,0.975248,0.102602,0.090325,0.069064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3258,1758913200,2025-09-26 19:00:00,59.877178,28.977748,0.483953,0.015688,0.007593,0,0,0.000007,0.0,0.999789,0.999803,0.000000,0.015688,0.007593,0.999799,0.088353,0.105727,0.069521
3259,1758916800,2025-09-26 20:00:00,59.877178,28.977748,0.483953,0.015688,0.007593,0,0,0.000007,0.0,0.999789,0.999803,0.000000,0.015688,0.007593,0.999710,0.088353,0.105727,0.069521
3260,1758920400,2025-09-26 21:00:00,59.877178,28.977748,0.483953,0.015688,0.007593,0,0,0.000007,0.0,0.999789,0.999803,0.000000,0.015688,0.007593,0.999621,0.088353,0.105727,0.069521
3261,1758924000,2025-09-26 22:00:00,59.877178,28.977748,0.483953,0.015688,0.007593,0,0,0.000007,0.0,0.999789,0.999803,0.000000,0.015688,0.007593,0.999621,0.088353,0.105727,0.069521
3262,1758927600,2025-09-26 23:00:00,59.877178,28.977748,0.483953,0.015688,0.007593,0,0,0.000007,0.0,0.999789,0.999803,0.000000,0.015688,0.007593,0.999708,0.088353,0.105727,0.069521

In [61]:
# for ind in base_to_index['PT-USDe']:
# for ind in [3,11,12,]:
for ind in [2,]:
    print(all_markets_position[ind]['market_name'])
    all_markets_position[ind]['market_df']['rate_spread'] = all_markets_position[ind]['market_df']['implied_apy'] - all_markets_position[ind]['market_df']['borrow_rate']
    plot_market_features(all_markets_position[ind]['market_df'], ['implied_apy', 'borrow_rate'], y_ranges={"borrow_rate": [0,0.3]}, dates_range=['2025-07-01', '2025-09-25'])

eth_PT-USDe-27NOV2025_usds

In [66]:
import numpy as np
def add_position_features(positions_df, market_df):
    """
    Add features to positions DataFrame using hourly market data.

    Parameters:
    positions_df : DataFrame with columns 'opening_date', 'closing_date' (datetime)
    market_df    : DataFrame with columns 'timestamp', 'datetime', 'borrow_rate', 'implied_apy'

    Returns:
    positions_df with additional columns:
        - initial_implied_apy
        - close_implied_apy
        - implied_apy_diff
        - eff_borrow_rate_overall
        - eff_borrow_rate_last_24h
        - eff_borrow_rate_last_72h
        - spread_overall, spread_last_24h, spread_last_72h
    """
    df_pos = positions_df.copy()
    df_market = market_df.copy()

    # Convert dates to timestamps if not already
    if 'opening_date' in df_pos.columns:
        df_pos['open_ts'] = pd.to_datetime(df_pos['opening_date']).astype('int64') // 10**9
    if 'closing_date' in df_pos.columns:
        df_pos['close_ts'] = pd.to_datetime(df_pos['closing_date']).astype('int64') // 10**9

    # Market data: ensure sorted
    df_market = df_market.sort_values('timestamp')
    market_ts = df_market['timestamp'].values
    market_borrow = df_market['borrow_rate'].values
    market_apy = df_market['implied_apy'].values

    # 1. Get implied APY at open and close (using last available value ≤ timestamp)
    df_market_apy = df_market[['timestamp', 'implied_apy']].dropna()
    # Open APY
    df_pos = df_pos.sort_values('open_ts')
    df_pos = pd.merge_asof(
        df_pos,
        df_market_apy,
        left_on='open_ts',
        right_on='timestamp',
        direction='backward'
    ).rename(columns={'implied_apy': 'initial_implied_apy'}).drop(columns='timestamp')
    # Close APY
    df_pos = df_pos.sort_values('close_ts')
    df_pos = pd.merge_asof(
        df_pos,
        df_market_apy,
        left_on='close_ts',
        right_on='timestamp',
        direction='backward'
    ).rename(columns={'implied_apy': 'close_implied_apy'}).drop(columns='timestamp')
    # Restore original order
    df_pos = df_pos.sort_index()

    # Compute APY change
    df_pos['implied_apy_diff'] = df_pos['close_implied_apy'] - df_pos['initial_implied_apy']

    # 2. Compute effective borrow rates
    pos_opens = df_pos['open_ts'].values
    pos_closes = df_pos['close_ts'].values
    n_pos = len(df_pos)
    eff_overall = np.full(n_pos, np.nan)
    eff_last24 = np.full(n_pos, np.nan)
    eff_last72 = np.full(n_pos, np.nan)

    for i in range(n_pos):
        open_ts = pos_opens[i]
        close_ts = pos_closes[i]
        if np.isnan(open_ts) or np.isnan(close_ts):
            continue

        # Overall period
        left = np.searchsorted(market_ts, open_ts, side='left')
        right = np.searchsorted(market_ts, close_ts, side='right')
        if left < right:
            window_rates = market_borrow[left:right]
            eff_overall[i] = window_rates.mean()

        # Last 24h before close
        start24 = close_ts - 24 * 3600
        left24 = np.searchsorted(market_ts, start24, side='left')
        right24 = np.searchsorted(market_ts, close_ts, side='right')
        if left24 < right24:
            window24 = market_borrow[left24:right24]
            eff_last24[i] = window24.mean()

        # Last 72h before close
        start72 = close_ts - 72 * 3600
        left72 = np.searchsorted(market_ts, start72, side='left')
        right72 = np.searchsorted(market_ts, close_ts, side='right')
        if left72 < right72:
            window72 = market_borrow[left72:right72]
            eff_last72[i] = window72.mean()

    df_pos['eff_borrow_rate_overall'] = eff_overall
    df_pos['eff_borrow_rate_last_24h'] = eff_last24
    df_pos['eff_borrow_rate_last_72h'] = eff_last72

    # 3. Spreads (initial implied APY minus effective borrow rates)
    df_pos['spread_overall'] = df_pos['initial_implied_apy'] - df_pos['eff_borrow_rate_overall']
    df_pos['spread_last_24h'] = df_pos['initial_implied_apy'] - df_pos['eff_borrow_rate_last_24h']
    df_pos['spread_last_72h'] = df_pos['initial_implied_apy'] - df_pos['eff_borrow_rate_last_72h']

    # Drop helper columns
    df_pos.drop(columns=['open_ts', 'close_ts'], inplace=True)

    return df_pos
print(all_markets_position[0].keys())
for m in range(len(all_markets_position)):
    all_markets_position[m]['early_closing'] = all_markets_position[m]['positions_df'][all_markets_position[m]['positions_df']['days_to_expiry_after_close'] > 7]
    all_markets_position[m]['late_closing'] = all_markets_position[m]['positions_df'][all_markets_position[m]['positions_df']['days_to_expiry_after_close'] <= 7]
    all_markets_position[m]['early_closing'] = add_position_features(all_markets_position[m]['early_closing'], all_markets_position[m]['market_df'])
    all_markets_position[m]['late_closing'] = add_position_features(all_markets_position[m]['late_closing'], all_markets_position[m]['market_df'])
    all_markets_position[m]['positions_df_enriched'] = add_position_features(all_markets_position[m]['positions_df'], all_markets_position[m]['market_df'])
    print(all_markets_position[m]['market_name'], len(all_markets_position[m]['positions_df']), len(all_markets_position[m]['early_closing']))

dict_keys(['token', 'market_name', 'positions_df', 'market_df', 'raw_df', 'hourly_df', 'early_closing', 'positions_df_enriched', 'late_closing'])
eth_PT-syrupUSDC-28AUG2025_usdc 15 8
eth_PT-slvlUSD-25SEP2025_usdc 76 41
eth_PT-USDe-27NOV2025_usds 35 29
eth_PT-USDe-25SEP2025_dai 128 29
eth_PT-syrupUSDC-30OCT2025_usdc 10 3
eth_PT-stcUSD-23JUL2026_usdc 3 3
eth_PT-USDe-27NOV2025_usdc 2 2
eth_PT-wstUSR-27MAR2025_usr 51 9
eth_PT-sNUSD-5MAR2026_usdc 6 2
eth_PT-USD0++-31OCT2024_usdc 23 1
eth_PT-USDe-31JUL2025_dai 95 71
eth_PT-USDe-25SEP2025_usdt 116 55
eth_PT-USDe-25SEP2025_usdc 216 84
eth_PT-wstUSR-27MAR2025_usdc 10 10
eth_PT-slvlUSD-29MAY2025_usdc 35 13
eth_PT-mHYPER-20NOV2025_usdc 77 51
eth_PT-reUSD-25JUN2026_usdc 223 223
eth_PT-reUSD-18DEC2025_usdc 21 7
eth_PT-RLP-4SEP2025_usdc 63 28
eth_PT-csUSDL-31JUL2025_usdc 107 33
eth_PT-wstUSR-25SEP2025_usdc 60 45
eth_PT-stcUSD-29JAN2026_usdc 129 98
eth_PT-lvlUSD-29MAY2025_usdc 85 24
eth_PT-USR-29MAY2025_usdc 18 5
eth_PT-USDe-27MAR2025_dai 122 73
eth_PT-USD0++-27MAR2025_usdc 42 25

In [67]:
all_markets_position[0]['early_closing'].head()

,user_address,opening_date,closing_date,position_length_days,max_debt,max_ltv,min_ltv,initial_ltv,initial_debt,days_to_expiry_after_close,initial_implied_apy,close_implied_apy,implied_apy_diff,eff_borrow_rate_overall,eff_borrow_rate_last_24h,eff_borrow_rate_last_72h,spread_overall,spread_last_24h,spread_last_72h
0,0x594c5eE5a326295FF6212C31BB3311747D3bD562,2025-05-14 01:55:59,2025-05-19 09:55:59,5.333333,1.000000,0.500184,0.499441,0.000000,1.000000,100.461123,0.090325,0.089479,-8.457159e-04,0.156045,0.141420,0.153420,-0.065720,-0.051095,-0.063095
1,0xABfE00f81c2b9734C2FeCec3f1996E18611ce658,2025-05-20 11:26:59,2025-05-20 12:26:59,0.041667,149.968800,0.511602,0.511602,0.511602,149.968800,99.356262,0.088595,0.088595,4.503106e-12,0.096055,0.096929,0.133086,-0.007460,-0.008334,-0.044491
2,0xE126E7c4A06D93a6e07e0DBb97a2027362e856c3,2025-05-31 06:59:47,2025-06-06 11:59:47,6.208333,36746.764781,0.892149,0.837196,0.837196,22959.627354,82.375150,0.092288,0.099253,6.965582e-03,0.096903,0.158871,0.112556,-0.004616,-0.066583,-0.020268
3,0x5fF11eAc5a8ffE52FBeA6a1431f7795920E10D09,2025-06-04 19:53:23,2025-06-11 18:53:23,6.958333,21513.132461,0.803133,0.801416,0.803132,21513.132461,77.087928,0.098063,0.100229,2.166367e-03,0.105411,0.091128,0.095629,-0.007348,0.006935,0.002434
4,0x6B84C4cBa94bd0971694f7f122635503De96112f,2025-06-11 04:39:47,2025-06-25 02:39:47,13.916667,24981.423873,0.838084,0.832786,0.838084,24981.423873,63.764039,0.096347,0.088044,-8.302946e-03,0.100251,0.080989,0.085828,-0.003904,0.015358,0.010518

In [74]:
users_clusters

                                    user_address  cluster
0     0x002AFa1e35cE85272aAE5e0d7Ab541DFd442B667        2
1     0x00896485a15c549AA6948c7430bef1f02f752300        3
2     0x008E5d9ea233Dfb9AB48098d6E98E14374030c15       -1
3     0x00A2913501C4B09B92b825dC8A2937eFDaD9953b        0
4     0x00B8dF76c223eb4b05123389330b4afD157152b8        0
...                                          ...      ...
1617  0xfc9803f19a667Ac43E13fC57405f9fDCdaC54747        2
1618  0xfcB2f00cF544E934E2f163c2593c7CE3eF7fFA9D        2
1619  0xfd1fA2C22F65649AE02188a33F286f22bcFCd225        2
1620  0xff17d5A9f7dB38A1384CF0ce1c81b880D17dB838        2
1621  0xffb26bd72414BaeC53a7bb005d55d8436beF2B15        2

[1622 rows x 2 columns]

In [75]:
users_clusters = pd.read_csv("/Users/yegortrussov/Documents/ml/lending_protocols/dataset_collection/data/modelling_datasets/pt_users_clusters_mapping.csv")
all_markets_position[0]['early_closing']
for i in all_markets_position:
    if '2026' in i['market_name']:
        continue
    print(i['market_name'])
    
    early = i['early_closing']
    late = i['late_closing']
    
    # Early closing
    early_pos = early[early['spread_overall'] > 0]
    early_neg = early[early['spread_overall'] < 0]
    early_neg_72 = early[early['spread_last_72h'] < 0]
    market_max_debt = i['market_df']['total_borrow'].quantile(0.95)
    print(f"    Early ({len(early)} events):")
    print(f"        Positive spread: {len(early_pos)} events, mean overall {early_pos['spread_overall'].mean():.4f}, 24h {early_pos['spread_last_24h'].mean():.4f}, 72h {early_pos['spread_last_72h'].mean():.4f}, implied apy diff {early_pos['implied_apy_diff'].mean()}, debt {early_pos['max_debt'].mean()} (pct. {early_pos['max_debt'].mean() / market_max_debt})")
    print(f"        Negative spread: {len(early_neg)} events, mean overall {early_neg['spread_overall'].mean():.4f}, 24h {early_neg['spread_last_24h'].mean():.4f}, 72h {early_neg['spread_last_72h'].mean():.4f}, implied apy diff {early_neg['implied_apy_diff'].mean()}, debt {early_neg['max_debt'].mean()} (pct. {early_neg['max_debt'].mean() / market_max_debt})")
    print(f"        Negative spread 72h: {len(early_neg_72)} events, mean overall {early_neg_72['spread_overall'].mean():.4f}, 24h {early_neg_72['spread_last_24h'].mean():.4f}, 72h {early_neg_72['spread_last_72h'].mean():.4f}, implied apy diff {early_neg_72['implied_apy_diff'].mean()},  debt {early_neg_72['max_debt'].mean()} (pct. {early_neg_72['max_debt'].mean() / market_max_debt})")
    print(f"Early clusters {users_clusters[users_clusters['user_address'].isin(early_pos['user_address'].unique())]['cluster'].value_counts()}")
    # Late closing
    late_neg = late[late['spread_overall'] < 0]
    print(f"    Late ({len(late)} events): negative spread users {len(late_neg)}")

eth_PT-syrupUSDC-28AUG2025_usdc
    Early (8 events):
        Positive spread: 1 events, mean overall 0.0007, 24h -0.0008, 72h 0.0078, implied apy diff -0.01231514652578869, debt 15713.09962221284 (pct. 0.0022386332801133235)
        Negative spread: 7 events, mean overall -0.0151, 24h -0.0237, 72h -0.0230, implied apy diff -0.0011730103499520872, debt 983898.6819539367 (pct. 0.14017529237630655)
        Negative spread 72h: 5 events, mean overall -0.0189, 24h -0.0376, 72h -0.0348, implied apy diff -0.0004148986175256414,  debt 1368159.243468761 (pct. 0.19492060055382676)
Early clusters cluster
2    1
Name: count, dtype: int64
    Late (7 events): negative spread users 0
eth_PT-slvlUSD-25SEP2025_usdc
    Early (41 events):
        Positive spread: 40 events, mean overall 0.0213, 24h 0.0121, 72h 0.0155, implied apy diff 0.0024994478434475177, debt 167479.7002485108 (pct. 0.01829491901773462)
        Negative spread: 1 events, mean overall -0.0009, 24h 0.0046, 72h 0.0039, implied apy diff 0.0274406125039916, debt 28807.659337831064 (pct. 0.0031468517909578244)
        Negative spread 72h: 5 events, mean overall 0.0111, 24h -0.0263, 72h -0.0195, implied apy diff 0.021238545067161167,  debt 163411.16052268943 (pct. 0.017850485425520805)
Early clusters cluster
 2    19
-1    14
 3     7
Name: count, dtype: int64
    Late (35 events): negative spread users 7
eth_PT-USDe-27NOV2025_usds
    Early (29 events):
        Positive spread: 29 events, mean overall 0.0287, 24h 0.0255, 72h 0.0261, implied apy diff -0.01802437990141622, debt 9808466.256275734 (pct. 0.12759705018936462)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    19
 2     6
 0     4
Name: count, dtype: int64
    Late (6 events): negative spread users 1
eth_PT-USDe-25SEP2025_dai
    Early (29 events):
        Positive spread: 29 events, mean overall 0.0551, 24h 0.0521, 72h 0.0553, implied apy diff 0.018890326265558813, debt 4170748.8671326693 (pct. 0.009669063712873325)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    17
 2    11
 0     1
Name: count, dtype: int64
    Late (99 events): negative spread users 0
eth_PT-syrupUSDC-30OCT2025_usdc
    Early (3 events):
        Positive spread: 1 events, mean overall 0.0194, 24h 0.0174, 72h 0.0279, implied apy diff 0.0029364818235844, debt 146972.658 (pct. 0.00429058063045226)
        Negative spread: 2 events, mean overall -0.0071, 24h -0.0016, 72h -0.0016, implied apy diff 0.013816146341768205, debt 19845788.4 (pct. 0.5793591574365768)
        Negative spread 72h: 1 events, mean overall -0.0081, 24h -0.0056, 72h -0.0060, implied apy diff 0.014872452258657201,  debt 9498100.0 (pct. 0.2772785390198129)
Early clusters cluster
-1    1
Name: count, dtype: int64
    Late (7 events): negative spread users 0
eth_PT-USDe-27NOV2025_usdc
    Early (2 events):
        Positive spread: 1 events, mean overall 0.0193, 24h 0.0383, 72h 0.0367, implied apy diff -0.024104481030922692, debt 161832.38416135113 (pct. 0.996867280220646)
        Negative spread: 1 events, mean overall -0.0038, 24h 0.0024, 72h 0.0058, implied apy diff -0.0026450212430517983, debt 1169657.067218 (pct. 7.204941491969491)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    1
Name: count, dtype: int64
    Late (0 events): negative spread users 0
eth_PT-wstUSR-27MAR2025_usr
    Early (9 events):
        Positive spread: 8 events, mean overall 0.0806, 24h 0.0954, 72h 0.0965, implied apy diff -0.023691921013452088, debt 181038.12790607876 (pct. 0.014147238160790273)
        Negative spread: 1 events, mean overall -0.0116, 24h 0.0932, 72h 0.0720, implied apy diff -0.003945155564361702, debt 1500000.0 (pct. 0.11721761314387118)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
 2    5
-1    3
Name: count, dtype: int64
    Late (42 events): negative spread users 1
eth_PT-USD0++-31OCT2024_usdc
    Early (1 events):
        Positive spread: 1 events, mean overall 0.0707, 24h 0.0955, 72h 0.1041, implied apy diff 0.003616663472956194, debt 32796.038399896905 (pct. 0.004171062167864432)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    1
Name: count, dtype: int64
    Late (22 events): negative spread users 0
eth_PT-USDe-31JUL2025_dai
    Early (71 events):
        Positive spread: 68 events, mean overall 0.0295, 24h 0.0140, 72h 0.0193, implied apy diff 0.009564556991992648, debt 270363.6407746109 (pct. 0.030142267887016634)
        Negative spread: 3 events, mean overall -0.0109, 24h -0.0020, 72h -0.0109, implied apy diff 0.006768750192136103, debt 1000469.0095692553 (pct. 0.1115401642495066)
        Negative spread 72h: 13 events, mean overall 0.0133, 24h -0.0186, 72h -0.0146, implied apy diff 0.018914242929548998,  debt 629037.036652336 (pct. 0.07013000274484522)
Early clusters cluster
 2    36
-1    32
Name: count, dtype: int64
    Late (24 events): negative spread users 0
eth_PT-USDe-25SEP2025_usdt
    Early (55 events):
        Positive spread: 53 events, mean overall 0.0395, 24h 0.0381, 72h 0.0411, implied apy diff 0.008336063342803386, debt 617012.0065251255 (pct. 0.01298761082751931)
        Negative spread: 2 events, mean overall -0.0553, 24h 0.0251, 72h 0.0334, implied apy diff 0.005898724214116455, debt 35470.825276386495 (pct. 0.0007466325931242367)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    39
 2     9
 3     4
 0     1
Name: count, dtype: int64
    Late (61 events): negative spread users 0
eth_PT-USDe-25SEP2025_usdc
    Early (84 events):
        Positive spread: 82 events, mean overall 0.0398, 24h 0.0398, 72h 0.0412, implied apy diff 0.005234307135544827, debt 2729432.20646279 (pct. 0.008319671286657983)
        Negative spread: 2 events, mean overall -0.0205, 24h 0.0233, 72h 0.0304, implied apy diff 0.0008166660518845875, debt 125128.76538128911 (pct. 0.000381409068894515)
        Negative spread 72h: 3 events, mean overall 0.0200, 24h -0.0005, 72h -0.0021, implied apy diff 0.030664159909656735,  debt 3997869.9070555344 (pct. 0.01218603759227584)
Early clusters cluster
-1    42
 2    23
 0    10
 3     7
Name: count, dtype: int64
    Late (132 events): negative spread users 0
eth_PT-wstUSR-27MAR2025_usdc
    Early (10 events):
        Positive spread: 10 events, mean overall 0.1244, 24h 0.0789, 72h 0.1089, implied apy diff -0.04301600951308162, debt 1153317.8924489047 (pct. 0.23983885165217952)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    10
Name: count, dtype: int64
    Late (0 events): negative spread users 0
eth_PT-slvlUSD-29MAY2025_usdc
    Early (13 events):
        Positive spread: 13 events, mean overall 0.0369, 24h 0.0137, 72h 0.0292, implied apy diff 0.003748067986931702, debt 159446.69279392334 (pct. 0.010271453438256197)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 2 events, mean overall 0.0181, 24h -0.0678, 72h -0.0052, implied apy diff 0.01975822857186705,  debt 267097.9196049466 (pct. 0.017206276258254653)
Early clusters cluster
-1    8
 3    3
 2    2
Name: count, dtype: int64
    Late (22 events): negative spread users 0
eth_PT-mHYPER-20NOV2025_usdc
    Early (51 events):
        Positive spread: 46 events, mean overall 0.0612, 24h -0.0009, 72h 0.0304, implied apy diff 0.01914858996544428, debt 869422.6417502837 (pct. 0.02843065432173253)
        Negative spread: 5 events, mean overall -0.0924, 24h -0.1241, 72h -0.0170, implied apy diff 0.0943821848891099, debt 3147137.8265603893 (pct. 0.10291333967293456)
        Negative spread 72h: 12 events, mean overall 0.0125, 24h -0.2114, 72h -0.0844, implied apy diff 0.12526223893693617,  debt 1644734.6649346265 (pct. 0.053783833620424215)
Early clusters cluster
-1    26
 2    17
 0     2
 1     1
Name: count, dtype: int64
    Late (26 events): negative spread users 1
eth_PT-reUSD-18DEC2025_usdc
    Early (7 events):
        Positive spread: 6 events, mean overall 0.0266, 24h -0.0519, 72h -0.0195, implied apy diff -0.02231715460372258, debt 852940.9036325322 (pct. 0.09475156064199132)
        Negative spread: 1 events, mean overall -0.0247, 24h -0.1299, 72h -0.0802, implied apy diff 0.006875842654385289, debt 72009.9963090718 (pct. 0.007999451665467467)
        Negative spread 72h: 5 events, mean overall 0.0178, 24h -0.0670, 72h -0.0446, implied apy diff -0.0207362414404694,  debt 362101.24708377896 (pct. 0.04022512946146713)
Early clusters cluster
-1    5
 2    1
Name: count, dtype: int64
    Late (14 events): negative spread users 0
eth_PT-RLP-4SEP2025_usdc
    Early (28 events):
        Positive spread: 28 events, mean overall 0.0452, 24h 0.0364, 72h 0.0383, implied apy diff 0.02548617014838497, debt 213811.7286480509 (pct. 0.0317179761663343)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 1 events, mean overall 0.0375, 24h -0.0233, 72h -0.0122, implied apy diff 0.042797467235281814,  debt 94981.0 (pct. 0.014089989886446117)
Early clusters cluster
 2    20
-1     6
 0     2
Name: count, dtype: int64
    Late (35 events): negative spread users 0
eth_PT-csUSDL-31JUL2025_usdc
    Early (33 events):
        Positive spread: 33 events, mean overall 0.0326, 24h 0.0277, 72h 0.0295, implied apy diff 0.001323252493814938, debt 161301.2563573845 (pct. 0.008777577442367741)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
 2    13
 3    11
-1     9
Name: count, dtype: int64
    Late (74 events): negative spread users 0
eth_PT-wstUSR-25SEP2025_usdc
    Early (45 events):
        Positive spread: 44 events, mean overall 0.0174, 24h 0.0086, 72h 0.0102, implied apy diff 0.0088989776358173, debt 410145.14109683596 (pct. 0.045606898360949714)
        Negative spread: 1 events, mean overall -0.0363, 24h 0.0016, 72h 0.0120, implied apy diff 0.0006266695993858012, debt 14342.858403114182 (pct. 0.0015948824448998654)
        Negative spread 72h: 12 events, mean overall 0.0114, 24h -0.0112, 72h -0.0070, implied apy diff 0.019992489517182677,  debt 181523.8299122906 (pct. 0.020184900493422)
Early clusters cluster
 2    25
-1    18
 0     1
Name: count, dtype: int64
    Late (15 events): negative spread users 1
eth_PT-lvlUSD-29MAY2025_usdc
    Early (24 events):
        Positive spread: 24 events, mean overall 0.0397, 24h 0.0375, 72h 0.0387, implied apy diff -0.009021449533074872, debt 76242.1334539568 (pct. 0.005139251924025078)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    9
 3    8
 2    6
 1    1
Name: count, dtype: int64
    Late (61 events): negative spread users 0
eth_PT-USR-29MAY2025_usdc
    Early (5 events):
        Positive spread: 5 events, mean overall 0.0343, 24h 0.0217, 72h 0.0275, implied apy diff -0.027111288217409036, debt 74473.48700455108 (pct. 0.005560744808862706)
        Negative spread: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan, debt nan (pct. nan)
        Negative spread 72h: 0 events, mean overall nan, 24h nan, 72h nan, implied apy diff nan,  debt nan (pct. nan)
Early clusters cluster
-1    2
 2    2
 3    1
Name: count, dtype: int64
    Late (13 events): negative spread users 3
eth_PT-USDe-27MAR2025_dai
    Early (73 events):
        Positive spread: 69 events, mean overall 0.0613, 24h 0.0594, 72h 0.0623, implied apy diff -0.017013916330387954, debt 1075172.9049407763 (pct. 0.011082557011560945)
        Negative spread: 4 events, mean overall -0.0178, 24h 0.0211, 72h 0.0285, implied apy diff 0.000997215814492372, debt 1026180.1435512878 (pct. 0.01057755444987277)
        Negative spread 72h: 2 events, mean overall 0.0006, 24h 0.0106, 72h -0.0106, implied apy diff 0.014501072908926091,  debt 2054679.2871025752 (pct. 0.02117901245013423)
Early clusters cluster
-1    36
 2    18
 3    10
 0     5
Name: count, dtype: int64
    Late (49 events): negative spread users 0
eth_PT-USD0++-27MAR2025_usdc
    Early (25 events):
        Positive spread: 23 events, mean overall 0.1219, 24h 0.0682, 72h 0.0844, implied apy diff -0.0485510266128317, debt 740760.3029335781 (pct. 0.043277349341701625)
        Negative spread: 2 events, mean overall -0.0418, 24h -0.0498, 72h -0.0867, implied apy diff 0.008634151704220439, debt 2656231.0866738954 (pct. 0.15518466663916458)
        Negative spread 72h: 4 events, mean overall 0.0452, 24h -0.1181, 72h -0.0954, implied apy diff -0.06444605556178115,  debt 1995196.619343406 (pct. 0.11656513012205669)
Early clusters cluster
-1    12
 3     6
 2     3
 1     1
 0     1
Name: count, dtype: int64
    Late (17 events): negative spread users 0